### ISSUE TITLE
浏览器不弹出新页面（移动端）

### ISSUE THREAD

**Issue by I21b** [hmjz100/LinkSwift#116]
使用的是via浏览器
`稍后请在新标签页中授权助手获取信息`之后没有任何反应

**Comment by Msshang88** [comment]
Edge Canary和 狐猴浏览器 都没有反应

**Comment by hmjz100** [comment]
<p>拖动这个链接 <code class="hljs language-bash" style="font-size: smaller; word-break: break-word; white-space: pre-wrap; overflow-wrap: break-word;"><a href="https://openapi.baidu.com/oauth/2.0/authorize?client_id=IlLqBbU3GjQ0t46TRwFateTprHWl39zF&amp;response_type=token&amp;redirect_uri=oob&amp;confirm_login=0&amp;scope=basic,netdisk">https://openapi.baidu.com/oauth/2.0/authorize?client_id=IlLqBbU3GjQ0t46TRwFateTprHWl39zF&amp;response_type=token&amp;redirect_uri=oob&amp;confirm_login=0&amp;scope=basic,netdisk</a></code> 到随便两个标签页之间（会显示↑的箭头，然后松手打开，当然也可以先复制链接，再单独打开新标签页，再粘贴打开，注意：不是直接点击或者右键打开），等脚本弹出授权提示，点击授权就好啦</p>
